<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="Sonals-MacBook-Pro.local" failures="1" tests="4" name="Test" time="2.736" errors="0" timestamp="2023-10-16T15:11:09 IST">
  <testcase classname="com.example.demo.test.TestNGTest" name="testPostRequest" time="2.709"/>
  <testcase classname="com.example.demo.test.TestNGTest" name="testTestNGONE" time="0.0"/>
  <testcase classname="com.example.demo.test.TestNGTest" name="testTestNGTWO" time="0.0"/>
  <testcase classname="com.example.demo.test.TestNGTest" name="testTestNGFOUR" time="0.0">
    <failure type="java.lang.AssertionError" message="expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [1]
at com.example.demo.test.TestNGTest.testTestNGFOUR(TestNGTest.java:96)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at com.example.demo.test.TestRunner.run(TestRunner.java:41)
at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:791)
at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:775)
at org.springframework.boot.SpringApplication.run(SpringApplication.java:345)
at com.example.demo.DemoApplication.main(DemoApplication.java:29)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- testTestNGFOUR -->
  <testcase classname="com.example.demo.test.TestNGTest" name="testTestNGTHREE" time="0.0">
    <ignored/>
  </testcase> <!-- testTestNGTHREE -->
</testsuite> <!-- Test -->
