<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="1" total="5" passed="3" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-10-16T00:18:30 IST" name="Suite" finished-at="2023-10-16T00:18:32 IST" duration-ms="2462">
    <groups>
    </groups>
    <test started-at="2023-10-16T00:18:30 IST" name="Test" finished-at="2023-10-16T00:18:32 IST" duration-ms="2462">
      <class name="com.example.demo.test.TestNGTest">
        <test-method is-config="true" signature="setup()[pri:0, instance:com.example.demo.test.TestNGTest@68ddd415]" started-at="2023-10-16T00:18:30 IST" name="setup" finished-at="2023-10-16T00:18:30 IST" duration-ms="4" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="testPostRequest()[pri:0, instance:com.example.demo.test.TestNGTest@68ddd415]" started-at="2023-10-16T00:18:30 IST" name="testPostRequest" finished-at="2023-10-16T00:18:32 IST" duration-ms="2446" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testPostRequest -->
        <test-method signature="testTestNGONE()[pri:0, instance:com.example.demo.test.TestNGTest@68ddd415]" started-at="2023-10-16T00:18:32 IST" name="testTestNGONE" finished-at="2023-10-16T00:18:32 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testTestNGONE -->
        <test-method signature="testTestNGTWO()[pri:0, instance:com.example.demo.test.TestNGTest@68ddd415]" started-at="2023-10-16T00:18:32 IST" name="testTestNGTWO" finished-at="2023-10-16T00:18:32 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testTestNGTWO -->
        <test-method signature="testTestNGFOUR()[pri:0, instance:com.example.demo.test.TestNGTest@68ddd415]" started-at="2023-10-16T00:18:32 IST" name="testTestNGFOUR" finished-at="2023-10-16T00:18:32 IST" duration-ms="0" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [2] but found [1]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [2] but found [1]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:907)
at org.testng.Assert.assertEquals(Assert.java:917)
at com.example.demo.test.TestNGTest.testTestNGFOUR(TestNGTest.java:96)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at com.example.demo.test.TestRunner.run(TestRunner.java:41)
at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:791)
at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:775)
at org.springframework.boot.SpringApplication.run(SpringApplication.java:345)
at com.example.demo.DemoApplication.main(DemoApplication.java:29)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testTestNGFOUR -->
      </class> <!-- com.example.demo.test.TestNGTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
